---
abstract: 'serialize / deserialize AMF data'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  YAML: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-AMF-XS
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  XSLoader: 0.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/Data-AMF-XS.git
version: 0.01_02
